CREATE TABLE PEDRO_PAIS(ID_PAIS NUMBER PRIMARY KEY,
                    NOME_PAIS VARCHAR2(30) NOT NULL);

CREATE TABLE PEDRO_ESTADO (ID_ESTADO NUMBER PRIMARY KEY,
                        NOME_ESTADO VARCHAR(30) NOT NULL,
                        ID_PAIS NUMBER);

ALTER TABLE PEDRO_ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY
(ID_PAIS) REFERENCES PEDRO_PAIS(ID_PAIS);